guoyingtao/Mantis

Example/CustomizedCropToolbar.swift, Example/Podfile, Example/Podfile.lock, Mantis.podspec, Mantis.xcodeproj/project.pbxproj, README.md, Sources/Mantis/CropView/CropView.swift, Sources/Mantis/CropViewController/CropToolbar.swift, Sources/Mantis/CropViewController/CropToolbarProtocol.swift, Sources/Mantis/CropViewController/CropViewController.swift
Add delegate?.cropViewDidBecomeUnResettable(self) to func reset() in CropView.swift
Hide reset button in the beginning.
=> Improve function namings of CropToolbarDelegate and CropToolbarProtocol

Example/Base.lproj/Main.storyboard, Example/EmbeddedCropViewController.swift, Sources/Mantis/CropView/CropView+Touches.swift, Sources/Mantis/CropView/CropView+UIScrollViewDelegate.swift, Sources/Mantis/CropView/CropView.swift, Sources/Mantis/CropViewController/CropViewController.swift
Fixes #65 
Adds two new delegate function to the CropViewController, which can be used to respond to the user starting and finishing a crop gesture (via pinch-to-zoom or dragging crop rectangle):
`func cropViewControllerDidBeginResize(_ cropViewController: CropViewController)`
`func cropViewControllerDidEndResize(_ cropViewController: CropViewController, cropped: UIImage, transformation: Transformation)`
Provides an example in the EmbeddedCropViewController for how to use these hooks to display the current resolution of the cropped area of a photo.
=> Resize begin and end events

Example/Base.lproj/Main.storyboard, Example/ViewController.swift, Sources/Mantis/Mantis.swift, Sources/Mantis/MaskBackground/CropVisualEffectView.swift
This PR adds two new background effects which are applied over the top of any cropped part of an image:
* Dark: Masks the cropped area with an opacity that is darker than the mask that appears when you perform cropping actions, making the cropped area appear to darken after an action.
* Light: Masks the cropped area with an opacity that is lighter than the mask that appears when you perform cropping actions (although still darker than the image itself), making the cropped area appear to lighten after an action.
=> Additional background crop effects

Example/EmbeddedCropViewController.swift, Sources/Mantis/CropViewController/CropViewController.swift, Sources/Mantis/Mantis.swift
Currently, if you load an embedded Mantis controller which is configured with a fixed ratio, there is an animation after the view loads:
This PR makes the animation duration configurable, so you can set it to 0 and have the embedded controller load with the fixed ratio already set:
=> Configurable animation when loading an embedded controller

Sources/Mantis/RotationDial/CGAngle.swift
If open pods project and set `BUILD_LIBRARY_FOR_DISTRIBUTION = YES`, this framework not gonna compile. error will say 
```
initializer for class 'CGAngle' is '@inlinable' and must delegate to another initializer
```
I was also surprised, but best guess is need to create `swiftinterface` in this mode, which has strict interface.
=> Fix build with BUILD_LIBRARY_FOR_DISTRIBUTION

Mantis.xcodeproj/project.pbxproj, Resource/Info.plist, Sources/Mantis/Resources/Info.plist
When install Mantis from Carthage, resources with localization files will not be copy to builded framework.
With CocoaPods everything work well, becouse CocoaPods authomatically generate Bundle with resources indicated in podspec file.
Create Bundle for resources the same as CocoaPods, put localizable resources into Bundle and link with Mantis target.
After this, Mantis framework will building with resources from new Bundle.
=> Fix getting resources from prebuilt framework

Sources/Mantis/Resources/Info.plist
- Use Mantis via Cartage
- Upload build to TestFlight
TestFlight uploading will be failed with error message:
> ERROR ITMS-90535: "Unexpected CFBundleExecutable Key. The bundle at 'Payload/ApplicantHH.app/Frameworks/Mantis.framework/Resource.bundle' does not contain a bundle executable. If this bundle intentionally does not contain an executable, consider removing the CFBundleExecutable key from its Info.plist and using a CFBundlePackageType of BNDL. If this bundle is part of a third-party framework, consider contacting the developer of the framework for an update to address this issue."
Removing `CFBundleExecutable` from resources bundle, whic was added in prevous PR: https://github.com/guoyingtao/Mantis/pull/84
=> Remove CFBundleExecutable key from resources bundle

CHANGELOG.md, Sources/Mantis/CropView/CropView.swift, Sources/Mantis/CropView/CropViewModel.swift, Sources/Mantis/CropViewController/CropViewController.swift, Sources/Mantis/Mantis.swift
=> fix: solve the issue when using normalizedTransform with presetFixedRatioType

Example/ImagePicker.swift, Sources/Mantis/CropView/CropView.swift, Sources/Mantis/CropViewController/CropToolbarProtocol.swift, Sources/Mantis/CropViewController/CropViewController.swift
Here's a warning.
`Using 'class' keyword for protocol inheritance is deprecated; use 'AnyObject' instead`
And i'm bit of cleanliness, i don't want any warning in my code, so after learn about 'class' and 'AnyObject', i choose fix this warning.
=> fix warning: use 'AnyObject' instead 'class'

SwiftUIExample/MantisSwiftUIExample/ContentView.swift
The cropViewControllerDidCrop delegate method was not updated to the latest, so the "Done" button does not work in the example.
=> fixed cropViewControllerDidCrop delegate method

Example/EmbeddedCropViewController.swift
=> fix: use round() instead of floor() for output image size

Example/Base.lproj/Main.storyboard, Example/ViewController.swift, Example/zh-Hans.lproj/Main.storyboard, Sources/Mantis/CropView/CropView+Touches.swift
Solve pan gesture conflict when presenting CropViewController without using fullscreen.
=> fix: solve pan gesture conflict

Sources/Mantis/CropViewController/CropViewController.swift, Sources/Mantis/Protocols/CropToolbarProtocol.swift
Normally if a user want a custom crop tool bar, the tool bar need to delegate operations to CropViewController. For some users who do not want the attached tool bar but still want to use these delegate functions, there is no need to pass a CropToolbarProtocol instance. So I change it to optional
=> fix: use optional CropToolbarProtocol for CropToolbarDelegate

Sources/Mantis/CropView/CropAuxiliaryIndicatorView.swift, Sources/Mantis/CropView/CropView.swift, Sources/Mantis/Protocols/CropOverlayViewProtocol.swift
To be consistent with the editor of current iOS Photo.app
=> feat: add 4 edge line handles on CropAuxiliaryIndicatorView

Sources/Mantis/RotationDial/RotationDial+Touches.swift
Solve the gesture conflict for rotation dial then CropViewController is presented as a non-fullscreen mode
=> fix: solve the gesture conflict for rotation dial

SwiftUIExample/MantisSwiftUIExample/ContentView.swift
CropViewControllerDelegate has the `cropViewControllerDidImageTransformed()` function that wasn't present in this example which causes a build error
=> Add missing function to conform

Sources/Mantis/CropView/CropAuxiliaryIndicatorView.swift, Sources/Mantis/CropView/CropView.swift, Sources/Mantis/Protocols/CropAuxiliaryIndicatorViewProtocol.swift, Tests/MantisTests/CropAuxiliaryIndicatorViewTests.swift
* use Core Graphics instead of UIViews to draw overlay indicator lines
* use two colors for rotating indicator lines
=> refactor: use Core Graphics instead of UIViews to draw overlay indicator lines

Sources/Mantis/CropData.swift
After changing CropRegion typealias into a struct it's properties are no longer accessible as they are internal. Code does not compile anymore.
=> make CropRegion props public

.swiftlint.yml, Sources/Mantis/CropView/CropAuxiliaryIndicatorView+Accessibility.swift, Sources/Mantis/CropView/CropView.swift, Sources/Mantis/Mantis.swift
Hi,
This PR resolves the following SwiftLint errors:
```
Identifier Name Violation: Variable name 'i' should be between 3 and 40 characters long (identifier_name)
Large Tuple Violation: Tuples should have at most 2 members (large_tuple)
Force Cast Violation: Force casts should be avoided (force_cast)
Line Length Violation: Line should be 200 characters or less; currently it has 221 characters (line_length)
```
=> Resolve SwiftLint errors

Example/CustomWaitingIndicator.swift, Mantis.xcodeproj/project.pbxproj, Sources/Mantis/CropView/CropAuxiliaryIndicatorView+Accessibility.swift, Sources/Mantis/CropViewController/CropToolbar.swift, Sources/Mantis/Extensions/CGImageExtensions.swift, Sources/Mantis/Extensions/UIImageExtensions.swift, Sources/Mantis/Protocols/RotationDialProtocol.swift, Sources/Mantis/RotationDial/RotationDial.swift, Sources/Mantis/RotationDial/RotationDialPlate.swift, SwiftUIExample/MantisSwiftUIExample/CameraView.swift, SwiftUIExample/MantisSwiftUIExample/CustomViewController.swift, SwiftUIExample/MantisSwiftUIExample/ImagePickerView.swift, SwiftUIExample/MantisSwiftUIExample/SourceTypeSelectionView.swift, Tests/MantisTests/CropWorkbenchViewTests.swift, Tests/MantisTests/Mock/FakeRotationDialView.swift
fix image processing logic for 24 and 48 bits images
fix more SwiftLint warnings
=> feat: output image processing errors

Example/ViewController.swift, Sources/Mantis/CropView/CropView.swift, Sources/Mantis/CropView/CropViewModel.swift, Sources/Mantis/CropViewController/CropViewController.swift, Sources/Mantis/Protocols/CropViewModelProtocol.swift, Sources/Mantis/Protocols/CropViewProtocol.swift, Tests/MantisTests/CropViewModelTests.swift, Tests/MantisTests/Mock/FakeCropView.swift
Also fix some unit test compile errors
=> fix: fix fix-ratio not changing when switch to free ratio, change crop box then switch back

Example/Base.lproj/Main.storyboard, Example/EmbeddedCropViewController.swift, Sources/Mantis/CropView/CropView.swift, Sources/Mantis/CropView/ImageContainer.swift, Sources/Mantis/CropViewController/CropViewController.swift, Sources/Mantis/Protocols/CropViewProtocol.swift, Sources/Mantis/Protocols/ImageContainerProtocol.swift
https://github.com/guoyingtao/Mantis/assets/26723384/a1e90f28-5699-44a7-8905-4398d1bb7654
=> feat: support updating image while cropping

Sources/Mantis/CropView/CropView+UIScrollViewDelegate.swift
use image center as zoom center
=> fix: fix image zoom center issue

Example/EmbeddedCropViewController.swift, Example/zh-Hans.lproj/Main.storyboard, Mantis.xcodeproj/project.pbxproj, Sources/Mantis/CropAuxiliaryIndicatorConfig.swift, Sources/Mantis/CropView/CropAuxiliaryIndicatorView.swift, Sources/Mantis/CropView/CropView+Touches.swift, Sources/Mantis/CropView/CropView+UIScrollViewDelegate.swift, Sources/Mantis/CropViewConfig.swift, Sources/Mantis/Mantis.swift, Sources/Mantis/MaskBackground/CropMaskProtocal.swift
Also make CropViewConfig.minimumCropBoxSize public
This PR fix #401 and #402
=> Add CropAuxiliaryIndicatorConfig to allow custom CropAuxiliaryIndicator colors

Sources/Mantis/CropView/CropView.swift, Sources/Mantis/RotationDial/SlideDial/SlideDial.swift
=> fix: fix the issue that rotation control jumps during orientation change
