guoyingtao/Mantis

Example/EmbeddedCropViewController.swift, Example/ViewController.swift, Mantis/Source/CropView/CropView+Touches.swift, Mantis/Source/CropView/CropView.swift, Mantis/Source/CropViewController/CropViewController.swift
Firstly thanks for sharing the lib! I've started using it and found that I need to get notified when user taps cancel, thus added a couple of delegate methods, and changed the delegate method name according to conventions (https://github.com/raywenderlich/swift-style-guide#delegates & https://docs.swift.org/swift-book/LanguageGuide/Protocols.html)
Also use `let` instead of unchanging `var`, as well as removed unnecessary `!` - there shouldn't be a reason to ever use `!` IMO, or at least 99% of time it shouldn't be present ;)
I've only looked at CropViewController and CropView, so the above philosophy could also apply to other files if you get time to review them. Let me know what you think :D
=> Add delegate methods and improve structure

Mantis/Source/CropViewController/CropViewController.swift
Because I need to do some animation as the cropVC starts to dismiss, needed this additional delegate call, and added default implementation :)
=> Add willDismiss delegate call

README.md
=> Add new delegate method & mark optional ones

Mantis.xcodeproj/xcshareddata/xcschemes/Mantis.xcscheme, README.md
Add xcsharedata folder to help Carthage can build the Mantis schema.
=> add carthage support

Mantis/Source/CropViewController/CropToolbar.swift, Mantis/Source/CropViewController/CropViewController.swift, Mantis/Source/Mantis.swift
So that we can customize the font size
=> Add optionButtonFontSize & optionButtonFontSizeForPad to config

Example/Base.lproj/Main.storyboard, Example/CustomizedCropToolbar.swift, Example/MantisExample.xcodeproj/project.pbxproj, Example/Podfile, Example/Podfile.lock, Example/ViewController.swift, Mantis.podspec, Mantis.xcodeproj/project.pbxproj, Mantis.xcodeproj/xcshareddata/xcschemes/Mantis-Package.xcscheme, Mantis.xcodeproj/xcshareddata/xcschemes/Mantis.xcscheme, README.md, Sources/Mantis/CropView/CropView.swift, Sources/Mantis/CropViewController/CropToolbar.swift, Sources/Mantis/CropViewController/CropToolbarProtocol.swift, Sources/Mantis/CropViewController/CropViewController.swift, Sources/Mantis/Mantis.swift
=> 33 customized toolbar

Example/CustomizedCropToolbar.swift, Example/EmbeddedCropViewController.swift, Example/Podfile.lock, Example/ViewController.swift, Mantis.podspec, Mantis.xcodeproj/project.pbxproj, README.md, Sources/Mantis/CropView/CropView.swift, Sources/Mantis/CropViewController/CropToolbar.swift, Sources/Mantis/CropViewController/CropToolbarProtocol.swift, Sources/Mantis/CropViewController/CropViewController.swift
=> #33 #36 #37 #38

Example/Podfile.lock, Example/ViewController.swift, Sources/Mantis/CropView/CropScrollView.swift, Sources/Mantis/CropView/CropView+UIScrollViewDelegate.swift, Sources/Mantis/CropViewController/CropViewController.swift, Sources/Mantis/Mantis.swift
=> Normalized input

Example/Podfile.lock, Example/ViewController.swift, Sources/Mantis/CropView/CropScrollView.swift, Sources/Mantis/CropView/CropView.swift, Sources/Mantis/CropViewController/CropViewController.swift, Sources/Mantis/Mantis.swift
Make saved transformation info can apply to different devices.
=> Improve transformation

Sources/Mantis/CropView/CropView.swift, Sources/Mantis/Info.plist
=> Fix fixed ratio break bug

Sources/Mantis/CropView/CropView.swift, Sources/Mantis/CropView/CropViewModel.swift
=> Fix clock rotation bug

Example/MantisExample.xcodeproj/project.pbxproj, Example/Podfile, Example/Podfile.lock, Mantis.xcodeproj/project.pbxproj, Sources/Mantis/CropViewController/CropToolbar.swift, Sources/Mantis/CropViewController/CropViewController.swift, Sources/Mantis/Mantis.swift
=> Add the feature to set default ratio

Example/ViewController.swift, Sources/Mantis/CropViewController/CropToolbar.swift, Sources/Mantis/CropViewController/CropToolbarProtocol.swift, Sources/Mantis/CropViewController/CropViewController.swift, Sources/Mantis/CropViewController/ToolBarButtonImageBuilder.swift, Sources/Mantis/ToolbarButtonOptions.swift
=> 85 rotate image cropper separately

.gitignore, Example/MantisExample.xcodeproj/xcshareddata/xcschemes/MantisExample.xcscheme, Sources/Mantis/Extensions/CGImageExtensions.swift
Improve the logic of getting bitmapInfo for creating CGContext
=> Add getBitmapInfo for CGImgeExtension

Sources/Mantis/CropViewController/CropToolbar.swift, Sources/Mantis/CropViewController/CropToolbarProtocol.swift, Sources/Mantis/CropViewController/CropViewController.swift
=> Fix the wrong auto zoom after an image appeared

Sources/Mantis/CropView/CropBoxLockedAspectFrameUpdater.swift
=> fix the wrong ratio issue for fixed ratio seleciton

Sources/Mantis/CropView/CropView.swift, Sources/Mantis/CropViewController/CropViewController.swift
=> fix: fix “keep zooming” issue

Sources/Mantis/CropView/CropView.swift, Sources/Mantis/CropView/ImageContainer.swift
=> Fix: fix the issue of manual crop not working sometime

Sources/Mantis/CropView/CropView.swift
=> fix the manual crop offset issue after rotation

Mantis.podspec, Sources/Mantis/CropViewController/CropToolbar.swift, Sources/Mantis/CropViewController/FixedRatioManager.swift, Sources/Mantis/CropViewController/RatioPresenter.swift, Sources/Mantis/Helpers/LocalizedHelper.swift, Sources/Mantis/Mantis.swift
* fix: add default value for localized string
* fix: add more default values for localized strings
* fix: support static lib localization
=> fix: support static lib localization (#141)

Example/Base.lproj/Main.storyboard, Example/CustomizedCropToolbar.swift, Example/CustomizedCropToolbarWithoutList.swift, Example/ViewController.swift, Sources/Mantis/CropView/CropView.swift, Sources/Mantis/CropViewController/CropToolbar.swift, Sources/Mantis/CropViewController/CropToolbarProtocol.swift, Sources/Mantis/CropViewController/CropViewController.swift, Sources/Mantis/Helpers/Orientation.swift
BREAKING CHANGE: refactor CropToolbarProtocol. Add heightForVerticalOrientation and widthForHorizonOrientation, remove heightForVerticalOrientationConstraint and widthForHorizonOrientationConstraint
fix example project autoLayout conflicts
=> feat: make CropToolBar Sizable

README.md
This is also shown in the google results, now it's very clear that we are doing image cropping.
I also get better search results now, hence this closes #174
=> README: Improve first sentence

Example/MantisExample.xcodeproj/project.pbxproj, Example/MyNavigationCropToolbar.swift, Example/ViewController.swift, Mantis.podspec, Mantis.xcodeproj/project.pbxproj, README.md, Sources/Mantis/Config.swift, Sources/Mantis/CropViewController/CropToolbar.swift, Sources/Mantis/CropViewController/CropToolbarProtocol.swift, Sources/Mantis/CropViewController/CropViewController.swift, Sources/Mantis/CropViewController/ToolBarButtonImageBuilder+DrawImage.swift, Sources/Mantis/CropViewController/ToolBarButtonImageBuilder.swift, Sources/Mantis/Helpers/Orientation.swift
This PR solves #173 
@vanniktech 
I added showBottomCropToolbar option to CropToolbarConfig, you can check the example `Hide Rotation Dial`
=> feat: add showAttachedCropToolbar option to CropToolbarConfig

Example/EmbeddedCropViewController.swift, Example/ViewController.swift, Mantis.xcodeproj/project.pbxproj, Sources/Mantis/Config.swift, Sources/Mantis/CropToolbarConfig.swift, Sources/Mantis/CropView/CropMaskViewManager.swift, Sources/Mantis/CropView/CropView+Touches.swift, Sources/Mantis/CropView/CropView+UIScrollViewDelegate.swift, Sources/Mantis/CropView/CropView.swift, Sources/Mantis/CropView/CropViewConfig.swift, Sources/Mantis/CropViewConfig.swift, Sources/Mantis/CropViewController/CropViewController.swift, Sources/Mantis/Enum.swift, Sources/Mantis/Extensions/CGImageExtensions.swift, Sources/Mantis/Extensions/UIImageExtensions.swift, Sources/Mantis/Global.swift, Sources/Mantis/Mantis.swift, Sources/Mantis/MaskBackground/CropVisualEffectView.swift, Sources/Mantis/RotationDial/RotationDial.swift, Sources/Mantis/RotationDial/RotationDialPlate.swift
split config into 3 config files
put dial config into CropView Config
add Global.swift
=> feat: refactor configs and add zoom scale limitation settings

Example/ViewController.swift, Sources/Mantis/CropView/CropView.swift, Sources/Mantis/CropViewConfig.swift, Sources/Mantis/RotationDial/RotationDialPlate.swift
make hiding rotation dial easier and less confusing for users.
=> fix: restore showRotationDial setting

Example/MantisExample.xcodeproj/project.pbxproj, Example/Podfile, Example/ViewController.swift, Sources/Mantis/CropView/CropScrollView.swift, Sources/Mantis/CropView/CropView.swift, Sources/Mantis/CropViewConfig.swift
=> fix: solve the issue of initial minimum zoom scale is not working

Example/ViewController.swift, Sources/Mantis/CropView/CropView.swift, Sources/Mantis/CropViewConfig.swift, Sources/Mantis/Extensions/CGImageExtensions.swift, Sources/Mantis/Extensions/UIImageExtensions.swift
=> feat: support adding border to cropped image

Example/ViewController.swift, Sources/Mantis/CropView/CropView.swift
fixed #201 
I removed some old code for solving some bug when using alwaysUsingOnePresetFixedRatio. 
I totally forgot what the bug was but looks it works fine now.
=> fix: fix the weird rotation animation issue for alwaysUsingOnePresetFixedRatio

Example/ViewController.swift, Sources/Mantis/CropViewController/CropViewController.swift
present full screen for mac catalyst as #215 suggested
=> fix: present full screen for mac catalyst

Example/EmbeddedCropViewController.swift, README.md, Sources/Mantis/CropToolbarConfig.swift, Sources/Mantis/CropViewController/CropToolbar.swift, Sources/Mantis/CropViewController/CropViewController.swift, Sources/Mantis/Mantis.swift
We can use CropToolbarConfig.mode instead.
Fix #213
=> refactor: remove CropViewControllerMode

Sources/Mantis/CropView/CropView.swift, Sources/Mantis/CropViewConfig.swift
Make CropViewConfig.padding public
Also renamed minimumBoxSize to minimumCropBoxSize
=> feat: make CropViewConfig.padding public

Example/CustomizedCropToolbar.swift, Example/CustomizedCropToolbarWithoutList.swift, Example/MyNavigationCropToolbar.swift, Sources/Mantis/CropViewController/CropToolbar.swift, Sources/Mantis/CropViewController/CropToolbarProtocol.swift, Sources/Mantis/CropViewController/CropViewController.swift
=> refactor: make CropToolbarDelegate conform to Apple's naming convention

Example/ViewController.swift, Sources/Mantis/Config.swift, Sources/Mantis/CropView/CropView.swift, Sources/Mantis/CropViewController/CropViewController.swift
=> feat: support async crop

Mantis.xcodeproj/project.pbxproj, Sources/Mantis/CropView/CropView.swift, Sources/Mantis/CropView/ImageContainer.swift, Sources/Mantis/CropViewController/CropViewController.swift, Sources/Mantis/Protocols/CropViewControllerDelegate.swift, Sources/Mantis/Protocols/ImageContainerProtocol.swift, Sources/Mantis/TypeAlias.swift
Also add getCropRegion to ImageContainerProtocol
=> feat: add CropRegion into CropInfo

Example/ViewController.swift, Sources/Mantis/CropView/CropView.swift, Sources/Mantis/CropViewController/CropViewController.swift, Sources/Mantis/Protocols/CropViewProtocol.swift
=> fix: fix the issue when using canUseMultiplePresetFixedRatio with default ratio > 0

Sources/Mantis/CropViewController/CropViewController.swift, Sources/Mantis/MaskBackground/CropVisualEffectView.swift, Sources/Mantis/Protocols/CropToolbarProtocol.swift
Allow to select free ratio if config.presetFixedRatioType is equal. to.canUseMultiplePresetFixedRatio(defaultRatio: 0)
=> Allow to select free ratio

Sources/Mantis/Extensions/CGImageExtensions.swift
=> fix: add 48 and 24 bit image cases for getBitmapInfo()

Example/Base.lproj/Main.storyboard, Example/CustomViewController.swift, Example/EmbeddedCropViewController.swift, Example/MantisExample.xcodeproj/project.pbxproj, Example/ViewController.swift, README.md, Sources/Mantis/CropViewController/CropViewController.swift, Sources/Mantis/Mantis.swift
References #270
My main goal is to have my own version of `CropViewController` which behaves a bit different as the actions are in the navigation bar. So all of the set up code can go into its own Controller. Also in my own ViewController I'd also link my features together and implement other interfaces that belong to the image editing section.
=> Open up CropViewController for inhertiance.

Sources/Mantis/Protocols/CropViewControllerDelegate.swift, SwiftUIExample/MantisSwiftUIExample/ContentView.swift, SwiftUIExample/Podfile.lock
remove Self: UIViewController limitation for CropViewController delegate
=> refactor: remove Self: UIViewController limitation for CropViewController delegate

Sources/Mantis/CropView/CropView.swift, Sources/Mantis/CropView/CropViewStatus.swift, Sources/Mantis/CropViewController/RatioItemView.swift, Sources/Mantis/Protocols/CropViewModelProtocol.swift
move `translatesAutoresizingMaskIntoConstraints = false` to init function RationItemView
=> refactor: remove associated parameter from CropViewStatus.rotating

Example/CustomWaitingIndicator.swift, Example/MantisExample.xcodeproj/project.pbxproj, Example/ViewController.swift, Sources/Mantis/CropView/CropView.swift, Sources/Mantis/CropViewConfig.swift, Sources/Mantis/Protocols/CropViewProtocol.swift
=> feat: support custom waiting animation for async crop

Example/CustomizedCropToolbar.swift, Example/CustomizedCropToolbarWithoutList.swift, Mantis.xcodeproj/project.pbxproj, Sources/Mantis/CropToolbarConfig.swift, Sources/Mantis/CropView/CropAuxiliaryIndicatorView+Accessibility.swift, Sources/Mantis/CropView/CropAuxiliaryIndicatorView.swift, Sources/Mantis/CropView/CropBoxFreeAspectFrameUpdater.swift, Sources/Mantis/CropView/CropBoxLockedAspectFrameUpdater.swift, Sources/Mantis/CropView/CropView.swift, Sources/Mantis/CropView/CropViewModel.swift, Sources/Mantis/CropView/CropViewStatus.swift, Sources/Mantis/CropView/CropWorkbenchView.swift, Sources/Mantis/CropView/ImageContainer.swift, Sources/Mantis/CropViewController/CropToolbar.swift, Sources/Mantis/CropViewController/CropViewController.swift, Sources/Mantis/Definition.swift, Sources/Mantis/Enum.swift, Sources/Mantis/Helpers/GeometryHelper.swift, Sources/Mantis/Mantis.swift, Sources/Mantis/Protocols/CropAuxiliaryIndicatorViewProtocol.swift, Sources/Mantis/Protocols/CropToolbarProtocol.swift, Sources/Mantis/Protocols/CropViewModelProtocol.swift, Sources/Mantis/Protocols/RotationDialViewModelProtocol.swift, Sources/Mantis/RotationDial/RotationDial.swift, Sources/Mantis/RotationDial/RotationDialPlate.swift, Sources/Mantis/RotationDial/RotationDialViewModel.swift, Tests/MantisTests/CropAuxiliaryIndicatorViewTests.swift, Tests/MantisTests/ImageContainerTests.swift, Tests/MantisTests/Mock/FakeCropAuxiliaryIndicatorView.swift
fix #179 
Improve accessibilities for VoiceOver
Improve accessibilities for Dynamic Fonts to make sure `Cancel` and `Done` button and rotation dial to show the whole text
=> chore: improve accesibilities

Sources/Mantis/CropViewController/CropToolbar.swift, Sources/Mantis/RotationDial/RotationDialPlate.swift
fix cropToolBar button display issue when using bigger dynamic fonts
=> fix: fix resetting rotation dial caused UI issue

Sources/Mantis/CropView/CropView.swift
=> fix: add guard to make sure scaleX and scaleY are not infinite

Example/ViewController.swift, Mantis.xcodeproj/project.pbxproj, Sources/Mantis/CropView/CropView.swift, Sources/Mantis/CropViewController/CropToolbar.swift, Sources/Mantis/CropViewController/CropViewController.swift, Sources/Mantis/CropViewController/ToolBarButtonImageBuilder.swift, Sources/Mantis/Helpers/ImageAutoAdjustHelper.swift, Sources/Mantis/Protocols/CropToolbarProtocol.swift, Sources/Mantis/Protocols/CropViewProtocol.swift, Sources/Mantis/ToolbarButtonOptions.swift
Only support fetch horizon and adjust angle.
TBD: find the main content and zoom in
This PR fix #320
=> feat: support auto adjusting an image

Example/ViewController.swift, Sources/Mantis/CropView/CropView.swift, Sources/Mantis/RotationDial/RotationDial/RotationDial.swift, Sources/Mantis/RotationDial/SlideDial/SlideDial.swift
=> fix: fix flip animation issue

Sources/Mantis/Extensions/UIImageExtensions.swift
=> fix: remove unnecessary checking logic for image origentations

Sources/Mantis/CropView/CropBoxLockedAspectFrameUpdater.swift, Sources/Mantis/CropView/CropView.swift
It also loosed dragging outside restrictions for fix ratios
=> fix: fix wrong fix ratios when dragging CropBox outside

Sources/Mantis/CropView/CropView.swift, Sources/Mantis/Enum.swift, Sources/Mantis/RotationDial/RotationDial/RotationDial.swift, Sources/Mantis/RotationDial/RotationDial/RotationDialConfig.swift, Sources/Mantis/RotationDial/SlideDial/SlideDialConfig.swift, Tests/MantisTests/RotateDialTests.swift
deprecate some enum definitions and properties
=> fix: fix flip issue when rotating angle is exact 45 or -45 degrees

Sources/Mantis/CropView/CropView.swift, Sources/Mantis/CropViewConfig.swift
add a new property "fixCropBoxWhenRotating90Degree" in CropViewConfig
=> feat: support a new feature of fixing crop box when rotating 90 degree

Example/ViewController.swift, Sources/Mantis/CropData.swift, Sources/Mantis/CropView/CropView+UIScrollViewDelegate.swift, Sources/Mantis/CropView/CropView.swift, Sources/Mantis/CropViewController/CropViewController.swift, Sources/Mantis/Protocols/CropViewControllerDelegate.swift, Sources/Mantis/Protocols/CropViewProtocol.swift, Tests/MantisTests/Mock/FakeCropView.swift
Add cropViewControllerDidImageTransformed(_ cropViewController: CropViewController, transformation: Transformation) 
Fix #362
=> feat: Output realtime transformation for a special use case

Sources/Mantis/CropView/CropAuxiliaryIndicatorView.swift, Sources/Mantis/CropViewConfig.swift, Sources/Mantis/Enum.swift, Sources/Mantis/Mantis.swift
Support transparent style for CropAuxiliaryIndicatorView
This PR fixes #366
=> feat: Add cropAuxiliaryIndicatorStyle in CropViewConfig for the issue #366

Example/EmbeddedCropViewController.swift, Example/zh-Hans.lproj/Main.storyboard, Mantis.xcodeproj/project.pbxproj, Sources/Mantis/CropAuxiliaryIndicatorConfig.swift, Sources/Mantis/CropView/CropAuxiliaryIndicatorView.swift, Sources/Mantis/CropView/CropView+Touches.swift, Sources/Mantis/CropView/CropView+UIScrollViewDelegate.swift, Sources/Mantis/CropViewConfig.swift, Sources/Mantis/Mantis.swift, Sources/Mantis/MaskBackground/CropMaskProtocal.swift
feat: change the value of minOverLayerUnit
avoid that the cropping masks can not cover the image in case of a small minimumCropBoxSize
=> feat: add CropAuxiliaryIndicatorConfig to allow custom CropAuxiliaryIndicator colors  also fix some compile warnings

Example/ViewController.swift, Sources/Mantis/Config.swift, Sources/Mantis/CropViewController/CropViewController.swift, SwiftUIExample/MantisSwiftUIExample/ContentView.swift, SwiftUIExample/MantisSwiftUIExample/ImageCropper.swift, SwiftUIExample/Podfile.lock
1. Refactor Mantis.Config
2. Improve example projects by supporting restoring transformation of an cropped image.
=> Refactor code

Example/MantisExample.xcodeproj/xcshareddata/xcschemes/MantisExample.xcscheme, Sources/Mantis/Extensions/CGImageExtensions.swift, Sources/Mantis/Extensions/UIImageExtensions.swift
convert 10-bit image to 16-bit image to preserve accuracy
=> fix: use createBackupCGContext in cgImageWithFixedOrientation
